name: food
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^7.7.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  loading_animation_widget: ^1.2.1
  #device_preview: ^1.1.0
  pin_code_fields: ^8.0.1
  intl: 0.19.0
  dio: ^5.4.3+1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  flutter_lints: ^4.0.0

  flutter_localizations:
    sdk: flutter

flutter_intl:
  main_locale: en
  enabled: true
  output_dir: lib/core/translations
  arb_dir: lib/core/translations


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/bb_activated/
    - assets/icons/bb_unactivated/
    - assets/images/

  fonts:
    - family: koHo_regular
      fonts:
        - asset: assets/fonts/KoHo-Regular.ttf
          weight: 400

    - family: koHo_semi_bold
      fonts:
        - asset: assets/fonts/KoHo-SemiBold.ttf
          weight: 600

    - family: koHo
      fonts:
        - asset: assets/fonts/KoHo-Regular.ttf
        - asset: assets/fonts/KoHo-Italic.ttf
          style: italic
        - asset: assets/fonts/KoHo-Bold.ttf
          weight: 700
        - asset: assets/fonts/KoHo-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/KoHo-Medium.ttf
          weight: 500
        - asset: assets/fonts/KoHo-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/KoHo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/KoHo-SemiBoldItalic.ttf
          weight: 600
          style: italic

